application:
  name: node-postgresql
  project: MyFullstackProject
  cloud_region: aws/us-east-2
databases:
- type: postgresql
  version: "11"
  name: my-postgresql
routers:
- name: main
  routes:
  - application_name: node-postgresql
    paths:
    - /
